version: '3.8'

volumes:
  kube:
  vscode_cache:
  bundle:

services:
  hetzner-k3s:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ${PWD}:/home/app/hetzner-k3s:cached
      - ${HOME}/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - kube:/root/.kube
      - vscode_cache:/vscode/vscode-server
      - bundle:/bundle
